# Generated by Django 4.2.17 on 2025-05-29 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Баланс')),
            ],
        ),
    ]
