# Generated by Django 4.2.17 on 2025-05-29 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_add_organization_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization')),
            ],
        ),
    ]
