# Generated by Django 4.2.17 on 2025-05-29 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_make_opid_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(unique=True, verbose_name='ID операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('payer_inn', models.CharField(max_length=12, verbose_name='ИНН плательщика')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('document_date', models.DateTimeField(verbose_name='Дата документа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization', verbose_name='Организация')),
            ],
        ),
    ]
