# Generated by Django 4.2.17 on 2025-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_add_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
