# Generated by Django 4.2.17 on 2025-05-29 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_update_payment_model_with_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
