# Generated by Django 4.2.17 on 2025-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_balance_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='operation_id',
            field=models.UUIDField(verbose_name='ID операции'),
        ),
    ]
